export const notifications = [
    {
    id: 1,
    design: 1,
    name:'Santhosh',
    ideaId: '14758',
    psID: '1264',
    info: 'submitted their idea',
    time: '1h',
    },
    {
        id: 2,
        design: 1,
        name:'Santhosh',
        ideaId: '14488',
        psID: '1964',
        info: 'accepted your proposal for this idea',
        time: '4h',
    },
    {
        id: 3,
        design: 2,
        name:'Santhosh',
        ideaId: '15658',
        psID: '',
        info: 'asking proposal for this idea',
        time: '5h',
    },
    {
        id: 4,
        design: 2,
        name:'Santhosh',
        ideaId: '17858',
        psID: '',
        info: 'wants investment for this idea',
        time: '5h',
    },
    {
        id: 5,
        design: 2,
        name:'Santhosh',
        ideaId: '12358',
        psID: '',
        info: 'accepted your proposal for this idea',
        time: '5h',
    },
    {
        id: 6,
        design: 2,
        name:'Santhosh',
        ideaId: '14638',
        psID: '',
        info: 'accepted your proposal for this idea',
        time: '5h',
    },
    {
        id: 7,
        design: 2,
        name:'Santhosh',
        ideaId: '12558',
        psID: '',
        info: 'accepted mentorship for this idea',
        time: '5h',
    },

    {
        id: 8,
        design: 2,
        name:'Santhosh',
        ideaId: '12547',
        psID: '',
        info: 'sent proposal for this idea',
        time: '5h',
    },
    {
        id: 9,
        design: 2,
        name:'Santhosh',
        ideaId: '12547',
        psID: '',
        info: 'requesting mentorship for this idea',
        time: '5h',
    },
    {
        id: 10,
        design: 12,
        name:'Santhosh',
        ideaId: '12547',
        psID: '',
        info: 'accepted mentorship for this idea',
        time: '5h',
    },
    {
        id: 11,
        design: 3,
        name:'',
        ideaId: '',
        psID: '',
        info: 'Your kyc is verified',
        time: '5h',
    },

]